### ISSUE TITLE
generate flat and arc image in the SimulatedCamera class.

### ISSUE THREAD

**Issue by christhechris** [openhsi/openhsi#20]
I think we should add a way to generate  flat and arc image (perhaps using real sample data) in the SimulatedCamera class. 

With this we can then get some tests and examples running in calibrate notebook without need for hardware etc.

**Comment by YiweiMao** [comment]
I agree. I put in an simulated HgAr pic implementation in the cameras notebook under WebCamera
Not extensively tested at the moment. Looks like it should belong in SimulatedCamera instead
![image](https://user-images.githubusercontent.com/46410481/150488326-3993c0e1-4f5a-4ef8-b300-8e410358e3e9.png)
