### ISSUE TITLE
key error rad_fit , dark_current

### ISSUE THREAD

**Issue by henryliangt** [openhsi/openhsi#43]
**Describe the bug**
Hi, this is Henry from USYD,
I've been trying to post process the datacube since morning, and running into an error same as [disucssion29](https://github.com/openhsi/openhsi/discussions/29)

I have read over the [forum](https://robonationforum.vbulletin.net/forum/robotx/-2022-robotx-challenge/4206-getting-surface-reflectance) too.

Also the [quick start](https://openhsi.github.io/openhsi/tutorial_camera.html#Post-processing-Datacubes)

It looks like you have a typo here.
Using different name and caused the variable unknown.

dc2process = ProcessDatacube(fname = "path_to_datacube_file.nc", processing_lvl=4,
                             json_path=json_path, pkl_path=pkl_path)
dc2process.load_next_tfms([proced_dc.dn2rad])

dc2process  != proced_dc

I found both names were used in different places, and may get confused here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by henryliangt** [comment]
Today morning, I got same error as Yasmin = 
KeyError: 'rad_fit'

After read over explanation, 
I think it is caused by the code sequence:

**
![image](https://user-images.githubusercontent.com/23263731/192716028-81c03343-f49a-4263-8be8-2080e44940fa.png)
**
We should update the model and get a new pkl file first, before we can use the pickle file.
Please correct me if I am wrong.

**Comment by henryliangt** [comment]
Following this idea, I dived into Py6S docs and find below 2 links very helpful.
https://py6s.readthedocs.io/en/latest/introduction.html

https://github.com/robintw/Py6S/blob/83c80611fb762b82ea646d72d3be40426a92b6a1/Py6S/SixSHelpers/radiosonde.py

Most useful part, as I am quoting:

"""Imports radiosonde data from the University of Wyoming website (http://weather.uwyo.edu/upperair/sounding.html) for use in Py6S.
        Arguments:
        * ``url`` -- The URL of the sounding results page on the UoW website
        * ``base_profile`` -- One of the predefined Atmospheric Profiles to use for any parts of the profile which the radiosonde data does not cover (>40km normally)
        Return value:
        A value suitable for assigning to ``s.atmos_profile``, where ``s`` is a :class:`.SixS` instance.
        How to use:
        1. Go to http://weather.uwyo.edu/upperair/sounding.html and use the interface to select the sounding that you want. Ensure that the From and To date/times are the same, so that only one sounding is retrieved.
        #. Copy the URL of the page displaying the sounding. It will look something like http://weather.uwyo.edu/cgi-bin/sounding?region=europe&TYPE=TEXT%3ALIST&YEAR=2012&MONTH=02&FROM=2712&TO=2712&STNM=03808
        #. Call this function with the URL as the first argument, and one of the predefined atmospheric profiles (eg. ``AtmosProfile.MidlatitudeSummer`` or ``AtmosProfile.Tropical``) as the second argument, and store the result in the atmos_profile attribute of a SixS instance. For example::
              s.atmos_profile = SixSHelpers.Radiosonde.import_uow_radiosonde_data("http://weather.uwyo.edu/cgi-bin/sounding?region=europe&TYPE=TEXT%3ALIST&YEAR=2012&MONTH=02&FROM=2712&TO=2712&STNM=03808", AtmosProfile.MidlatitudeWinter)
        The water density, pressure and temperature values from the radiosonde sounding will be interpolated to the 6S atmospheric grid and used for the 6S parameterisation. As radiosonde data tends to end at an altitude of around 30-40km, the data from the selected base profile is used above that height. Ozone data is not imported from the radiosonde data, as most radiosondes do not collect ozone density measurements, so the entire profile is taken from the base profile selected.
        """
This is a text explanation of 
![image](https://user-images.githubusercontent.com/23263731/192716825-81d3149b-ff2e-430e-812b-a069fa876fad.png)


Over this code, we are constructing a link to grab our local sounding station code, and time , to get a return from UWYO public API service.

Please correct me if I am wrong.

**Comment by henryliangt** [comment]
After modify my code, 
it looks like this, and it did produced a new pkl file for my location.

![image](https://user-images.githubusercontent.com/23263731/192717523-cf80be39-57dd-49b7-944f-f2ff017d2623.png)

**Comment by henryliangt** [comment]
then I turn back to postProcess the datacube using this latest created pkl file.
Here is the code,
![image](https://user-images.githubusercontent.com/23263731/192718005-8fed132a-b0e3-41e6-ab6c-ea1246d958ba.png)

**Comment by henryliangt** [comment]
This is the next error I ran into:


![image](https://user-images.githubusercontent.com/23263731/192718244-3350569e-b18a-41c0-846d-ae78347ae97d.png)


A text version is here, just for any one else easier to search into here.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [63], line 46
     39 print(dir(proced_dc))
     44 proced_dc.load_next_tfms([proced_dc.dn2rad])
---> 46 proced_dc.collect()
     48 proced_dc.show(hist_eq=True)

File ~/.pyenv/versions/miniforge3/envs/openhsi/lib/python3.8/site-packages/openhsi/capture.py:66, in OpenHSI.collect(self)
     64 self.start_cam()
     65 for i in tqdm(range(self.n_lines)):
---> 66     self.put(self.get_img())
     68     if callable(getattr(self,"get_temp",None)):
     69         self.cam_temperatures.put( self.get_temp() )

File ~/.pyenv/versions/miniforge3/envs/openhsi/lib/python3.8/site-packages/openhsi/data.py:426, in DataCube.put(self, x)
    424 """Applies the composed tranforms and writes the 2D array into the data cube. Stores a timestamp for each push."""
    425 self.timestamps.update()
--> 426 self.dc.put( self.pipeline(x) )

File ~/.pyenv/versions/miniforge3/envs/openhsi/lib/python3.8/site-packages/openhsi/data.py:360, in pipeline(self, x)
    358 """Compose a list of transforms and apply to x."""
    359 for f in self.tfm_list:
--> 360     x = f(x)
    361 return x

File ~/.pyenv/versions/miniforge3/envs/openhsi/lib/python3.8/site-packages/openhsi/data.py:286, in dn2rad(self, x)
    282 @patch
    283 def dn2rad(self:CameraProperties, x:"Array['λ,x',np.int32]") -> "Array['λ,x',np.float32]":
    284     """Converts digital numbers to radiance (uW/cm^2/sr/nm). Use after cropping to useable area."""
--> 286     return np.float32( (x - self.dark_current) * self.settings["luminance"]/self.ref_luminance  *  self.spec_rad_ref/self.calibration['spec_rad_ref_luminance'] )

AttributeError: 'ProcessDatacube' object has no attribute 'dark_current'

**Comment by henryliangt** [comment]
Now I am curious, what is in this pkl file. 
and I decide to open it and take a good look.

My code runs:
import pandas as pd

obj = pd.read_pickle(r'/home/robotx2/Desktop/hsi/USYD_Calib_Mono12_bin2.pkl')
print(obj)

**Comment by henryliangt** [comment]
The OutPut is as below:

`{'HgAr_pic': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'smile_shifts': array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int16), 'wavelengths': array([427.32438857, 428.22047684, 429.11659527, 430.01274369,
       430.90892195, 431.80512986, 432.70136728, 433.59763404,
       434.49392997, 435.3902549 , 436.28660867, 437.18299112,
       438.07940208, 438.97584139, 439.87230888, 440.76880439,
       441.66532775, 442.5618788 , 443.45845737, 444.3550633 ,
       445.25169643, 446.14835658, 447.04504359, 447.94175731,
       448.83849756, 449.73526418, 450.632057  , 451.52887587,
       452.42572061, 453.32259106, 454.21948705, 455.11640843,
       456.01335502, 456.91032667, 457.8073232 , 458.70434445,
       459.60139026, 460.49846047, 461.3955549 , 462.29267339,
       463.18981578, 464.08698191, 464.9841716 , 465.88138469,
       466.77862103, 467.67588044, 468.57316276, 469.47046782,
       470.36779547, 471.26514553, 472.16251784, 473.05991223,
       473.95732855, 474.85476662, 475.75222628, 476.64970737,
       477.54720972, 478.44473317, 479.34227755, 480.2398427 ,
       481.13742845, 482.03503463, 482.93266109, 483.83030766,
       484.72797417, 485.62566047, 486.52336637, 487.42109173,
       488.31883636, 489.21660012, 490.11438284, 491.01218434,
       491.91000447, 492.80784306, 493.70569994, 494.60357496,
       495.50146794, 496.39937872, 497.29730714, 498.19525303,
       499.09321623, 499.99119658, 500.88919389, 501.78720803,
       502.68523881, 503.58328607, 504.48134965, 505.37942939,
       506.27752511, 507.17563666, 508.07376387, 508.97190657,
       509.8700646 , 510.7682378 , 511.666426  , 512.56462903,
       513.46284673, 514.36107894, 515.2593255 , 516.15758622,
       517.05586096, 517.95414955, 518.85245182, 519.7507676 ,
       520.64909674, 521.54743907, 522.44579441, 523.34416262,
       524.24254352, 525.14093695, 526.03934275, 526.93776074,
       527.83619076, 528.73463266, 529.63308626, 530.5315514 ,
       531.43002792, 532.32851565, 533.22701442, 534.12552407,
       535.02404444, 535.92257537, 536.82111667, 537.7196682 ,
       538.61822979, 539.51680127, 540.41538248, 541.31397325,
       542.21257342, 543.11118282, 544.00980129, 544.90842866,
       545.80706477, 546.70570946, 547.60436255, 548.50302389,
       549.40169331, 550.30037065, 551.19905573, 552.0977484 ,
       552.9964485 , 553.89515584, 554.79387028, 555.69259165,
       556.59131977, 557.4900545 , 558.38879565, 559.28754308,
       560.1862966 , 561.08505607, 561.9838213 , 562.88259215,
       563.78136844, 564.68015   , 565.57893668, 566.47772831,
       567.37652473, 568.27532576, 569.17413125, 570.07294103,
       570.97175493, 571.8705728 , 572.76939446, 573.66821975,
       574.5670485 , 575.46588056, 576.36471576, 577.26355393,
       578.1623949 , 579.06123852, 579.96008461, 580.85893302,
       581.75778357, 582.65663611, 583.55549047, 584.45434648,
       585.35320398, 586.2520628 , 587.15092278, 588.04978376,
       588.94864557, 589.84750804, 590.74637101, 591.64523432,
       592.5440978 , 593.44296128, 594.34182461, 595.24068761,
       596.13955012, 597.03841198, 597.93727303, 598.83613309,
       599.734992  , 600.6338496 , 601.53270572, 602.4315602 ,
       603.33041288, 604.22926358, 605.12811215, 606.02695841,
       606.92580222, 607.82464339, 608.72348176, 609.62231718,
       610.52114947, 611.41997847, 612.31880401, 613.21762594,
       614.11644409, 615.01525828, 615.91406836, 616.81287417,
       617.71167553, 618.61047228, 619.50926426, 620.4080513 ,
       621.30683324, 622.20560992, 623.10438116, 624.00314681,
       624.90190669, 625.80066065, 626.69940852, 627.59815013,
       628.49688533, 629.39561394, 630.29433579, 631.19305074,
       632.0917586 , 632.99045922, 633.88915243, 634.78783807,
       635.68651597, 636.58518597, 637.4838479 , 638.38250159,
       639.28114689, 640.17978363, 641.07841164, 641.97703075,
       642.87564081, 643.77424165, 644.67283311, 645.57141501,
       646.4699872 , 647.3685495 , 648.26710176, 649.16564381,
       650.06417549, 650.96269663, 651.86120706, 652.75970662,
       653.65819515, 654.55667248, 655.45513845, 656.35359289,
       657.25203563, 658.15046652, 659.04888539, 659.94729207,
       660.84568639, 661.7440682 , 662.64243733, 663.54079361,
       664.43913688, 665.33746698, 666.23578373, 667.13408698,
       668.03237656, 668.9306523 , 669.82891405, 670.72716163,
       671.62539488, 672.52361363, 673.42181773, 674.320007  ,
       675.21818129, 676.11634042, 677.01448423, 677.91261256,
       678.81072525, 679.70882212, 680.60690301, 681.50496776,
       682.40301621, 683.30104818, 684.19906352, 685.09706206,
       685.99504363, 686.89300807, 687.79095522, 688.6888849 ,
       689.58679697, 690.48469124, 691.38256755, 692.28042575,
       693.17826567, 694.07608713, 694.97388998, 695.87167406,
       696.76943919, 697.66718521, 698.56491196, 699.46261928,
       700.36030699, 701.25797493, 702.15562295, 703.05325086,
       703.95085852, 704.84844575, 705.74601239, 706.64355827,
       707.54108323, 708.43858711, 709.33606974, 710.23353095,
       711.13097059, 712.02838848, 712.92578446, 713.82315837,
       714.72051003, 715.6178393 , 716.515146  , 717.41242996,
       718.30969103, 719.20692904, 720.10414382, 721.0013352 ,
       721.89850303, 722.79564714, 723.69276736, 724.58986353,
       725.48693549, 726.38398307, 727.2810061 , 728.17800442,
       729.07497786, 729.97192627, 730.86884947, 731.7657473 ,
       732.6626196 , 733.5594662 , 734.45628693, 735.35308164,
       736.24985016, 737.14659231, 738.04330795, 738.9399969 ,
       739.83665899, 740.73329407, 741.62990197, 742.52648252,
       743.42303556, 744.31956092, 745.21605844, 746.11252796,
       747.00896931, 747.90538232, 748.80176683, 749.69812268,
       750.5944497 , 751.49074772, 752.38701658, 753.28325613,
       754.17946618, 755.07564658, 755.97179716, 756.86791776,
       757.76400821, 758.66006835, 759.55609801, 760.45209703,
       761.34806524, 762.24400249, 763.13990859, 764.0357834 ,
       764.93162674, 765.82743845, 766.72321836, 767.61896631,
       768.51468214, 769.41036568, 770.30601676, 771.20163523,
       772.09722091, 772.99277364, 773.88829326, 774.7837796 ,
       775.6792325 , 776.57465179, 777.47003731, 778.36538889,
       779.26070637, 780.15598958, 781.05123836, 781.94645254,
       782.84163197, 783.73677646, 784.63188587, 785.52696002,
       786.42199875, 787.31700189, 788.21196929, 789.10690077,
       790.00179617, 790.89665533, 791.79147807, 792.68626425,
       793.58101368, 794.47572622, 795.37040168, 796.26503991,
       797.15964075, 798.05420402, 798.94872956, 799.84321722,
       800.73766681, 801.63207819, 802.52645118, 803.42078561,
       804.31508134, 805.20933818, 806.10355597, 806.99773456,
       807.89187377, 808.78597344, 809.68003341, 810.57405351,
       811.46803357, 812.36197344, 813.25587294, 814.14973191,
       815.04355019, 815.93732761, 816.83106401, 817.72475923,
       818.61841309, 819.51202543, 820.40559609, 821.29912491,
       822.19261171, 823.08605634, 823.97945863, 824.87281841,
       825.76613552, 826.6594098 , 827.55264108, 828.44582919,
       829.33897397, 830.23207526, 831.12513289, 832.0181467 ,
       832.91111652, 833.80404218, 834.69692353, 835.58976039,
       836.48255261, 837.37530001, 838.26800244, 839.16065972,
       840.0532717 , 840.94583821, 841.83835908, 842.73083415,
       843.62326325, 844.51564622, 845.4079829 , 846.30027312,
       847.19251671, 848.08471352, 848.97686336, 849.86896609,
       850.76102154, 851.65302954, 852.54498992, 853.43690253,
       854.32876719, 855.22058374, 856.11235202, 857.00407187,
       857.89574311, 858.78736559, 859.67893913, 860.57046358,
       861.46193876, 862.35336452, 863.24474069, 864.13606711,
       865.0273436 , 865.91857001, 866.80974617, 867.70087191,
       868.59194707, 869.48297149, 870.37394501, 871.26486744,
       872.15573864, 873.04655844, 873.93732667, 874.82804316,
       875.71870776, 876.60932029, 877.4998806 , 878.39038852,
       879.28084388, 880.17124651, 881.06159626, 881.95189297,
       882.84213645, 883.73232655, 884.62246311, 885.51254596,
       886.40257494, 887.29254987, 888.1824706 , 889.07233696,
       889.96214879, 890.85190591, 891.74160818, 892.63125541,
       893.52084746, 894.41038414, 895.29986531, 896.18929078,
       897.0786604 , 897.96797401]), 'wavelengths_linear': array([427.3663514 , 428.26384223, 429.16133307, 430.05882391,
       430.95631474, 431.85380558, 432.75129642, 433.64878725,
       434.54627809, 435.44376893, 436.34125976, 437.2387506 ,
       438.13624143, 439.03373227, 439.93122311, 440.82871394,
       441.72620478, 442.62369562, 443.52118645, 444.41867729,
       445.31616813, 446.21365896, 447.1111498 , 448.00864063,
       448.90613147, 449.80362231, 450.70111314, 451.59860398,
       452.49609482, 453.39358565, 454.29107649, 455.18856733,
       456.08605816, 456.983549  , 457.88103983, 458.77853067,
       459.67602151, 460.57351234, 461.47100318, 462.36849402,
       463.26598485, 464.16347569, 465.06096653, 465.95845736,
       466.8559482 , 467.75343903, 468.65092987, 469.54842071,
       470.44591154, 471.34340238, 472.24089322, 473.13838405,
       474.03587489, 474.93336573, 475.83085656, 476.7283474 ,
       477.62583823, 478.52332907, 479.42081991, 480.31831074,
       481.21580158, 482.11329242, 483.01078325, 483.90827409,
       484.80576493, 485.70325576, 486.6007466 , 487.49823743,
       488.39572827, 489.29321911, 490.19070994, 491.08820078,
       491.98569162, 492.88318245, 493.78067329, 494.67816413,
       495.57565496, 496.4731458 , 497.37063663, 498.26812747,
       499.16561831, 500.06310914, 500.96059998, 501.85809082,
       502.75558165, 503.65307249, 504.55056333, 505.44805416,
       506.345545  , 507.24303583, 508.14052667, 509.03801751,
       509.93550834, 510.83299918, 511.73049002, 512.62798085,
       513.52547169, 514.42296253, 515.32045336, 516.2179442 ,
       517.11543503, 518.01292587, 518.91041671, 519.80790754,
       520.70539838, 521.60288922, 522.50038005, 523.39787089,
       524.29536173, 525.19285256, 526.0903434 , 526.98783423,
       527.88532507, 528.78281591, 529.68030674, 530.57779758,
       531.47528842, 532.37277925, 533.27027009, 534.16776093,
       535.06525176, 535.9627426 , 536.86023343, 537.75772427,
       538.65521511, 539.55270594, 540.45019678, 541.34768762,
       542.24517845, 543.14266929, 544.04016013, 544.93765096,
       545.8351418 , 546.73263263, 547.63012347, 548.52761431,
       549.42510514, 550.32259598, 551.22008682, 552.11757765,
       553.01506849, 553.91255933, 554.81005016, 555.707541  ,
       556.60503183, 557.50252267, 558.40001351, 559.29750434,
       560.19499518, 561.09248602, 561.98997685, 562.88746769,
       563.78495853, 564.68244936, 565.5799402 , 566.47743103,
       567.37492187, 568.27241271, 569.16990354, 570.06739438,
       570.96488522, 571.86237605, 572.75986689, 573.65735773,
       574.55484856, 575.4523394 , 576.34983023, 577.24732107,
       578.14481191, 579.04230274, 579.93979358, 580.83728442,
       581.73477525, 582.63226609, 583.52975693, 584.42724776,
       585.3247386 , 586.22222943, 587.11972027, 588.01721111,
       588.91470194, 589.81219278, 590.70968362, 591.60717445,
       592.50466529, 593.40215613, 594.29964696, 595.1971378 ,
       596.09462864, 596.99211947, 597.88961031, 598.78710114,
       599.68459198, 600.58208282, 601.47957365, 602.37706449,
       603.27455533, 604.17204616, 605.069537  , 605.96702784,
       606.86451867, 607.76200951, 608.65950034, 609.55699118,
       610.45448202, 611.35197285, 612.24946369, 613.14695453,
       614.04444536, 614.9419362 , 615.83942704, 616.73691787,
       617.63440871, 618.53189954, 619.42939038, 620.32688122,
       621.22437205, 622.12186289, 623.01935373, 623.91684456,
       624.8143354 , 625.71182624, 626.60931707, 627.50680791,
       628.40429874, 629.30178958, 630.19928042, 631.09677125,
       631.99426209, 632.89175293, 633.78924376, 634.6867346 ,
       635.58422544, 636.48171627, 637.37920711, 638.27669794,
       639.17418878, 640.07167962, 640.96917045, 641.86666129,
       642.76415213, 643.66164296, 644.5591338 , 645.45662464,
       646.35411547, 647.25160631, 648.14909714, 649.04658798,
       649.94407882, 650.84156965, 651.73906049, 652.63655133,
       653.53404216, 654.431533  , 655.32902384, 656.22651467,
       657.12400551, 658.02149634, 658.91898718, 659.81647802,
       660.71396885, 661.61145969, 662.50895053, 663.40644136,
       664.3039322 , 665.20142304, 666.09891387, 666.99640471,
       667.89389554, 668.79138638, 669.68887722, 670.58636805,
       671.48385889, 672.38134973, 673.27884056, 674.1763314 ,
       675.07382224, 675.97131307, 676.86880391, 677.76629474,
       678.66378558, 679.56127642, 680.45876725, 681.35625809,
       682.25374893, 683.15123976, 684.0487306 , 684.94622144,
       685.84371227, 686.74120311, 687.63869394, 688.53618478,
       689.43367562, 690.33116645, 691.22865729, 692.12614813,
       693.02363896, 693.9211298 , 694.81862064, 695.71611147,
       696.61360231, 697.51109314, 698.40858398, 699.30607482,
       700.20356565, 701.10105649, 701.99854733, 702.89603816,
       703.793529  , 704.69101984, 705.58851067, 706.48600151,
       707.38349234, 708.28098318, 709.17847402, 710.07596485,
       710.97345569, 711.87094653, 712.76843736, 713.6659282 ,
       714.56341904, 715.46090987, 716.35840071, 717.25589154,
       718.15338238, 719.05087322, 719.94836405, 720.84585489,
       721.74334573, 722.64083656, 723.5383274 , 724.43581824,
       725.33330907, 726.23079991, 727.12829074, 728.02578158,
       728.92327242, 729.82076325, 730.71825409, 731.61574493,
       732.51323576, 733.4107266 , 734.30821744, 735.20570827,
       736.10319911, 737.00068994, 737.89818078, 738.79567162,
       739.69316245, 740.59065329, 741.48814413, 742.38563496,
       743.2831258 , 744.18061664, 745.07810747, 745.97559831,
       746.87308914, 747.77057998, 748.66807082, 749.56556165,
       750.46305249, 751.36054333, 752.25803416, 753.155525  ,
       754.05301584, 754.95050667, 755.84799751, 756.74548834,
       757.64297918, 758.54047002, 759.43796085, 760.33545169,
       761.23294253, 762.13043336, 763.0279242 , 763.92541504,
       764.82290587, 765.72039671, 766.61788754, 767.51537838,
       768.41286922, 769.31036005, 770.20785089, 771.10534173,
       772.00283256, 772.9003234 , 773.79781424, 774.69530507,
       775.59279591, 776.49028674, 777.38777758, 778.28526842,
       779.18275925, 780.08025009, 780.97774093, 781.87523176,
       782.7727226 , 783.67021344, 784.56770427, 785.46519511,
       786.36268594, 787.26017678, 788.15766762, 789.05515845,
       789.95264929, 790.85014013, 791.74763096, 792.6451218 ,
       793.54261264, 794.44010347, 795.33759431, 796.23508514,
       797.13257598, 798.03006682, 798.92755765, 799.82504849,
       800.72253933, 801.62003016, 802.517521  , 803.41501184,
       804.31250267, 805.20999351, 806.10748434, 807.00497518,
       807.90246602, 808.79995685, 809.69744769, 810.59493853,
       811.49242936, 812.3899202 , 813.28741104, 814.18490187,
       815.08239271, 815.97988354, 816.87737438, 817.77486522,
       818.67235605, 819.56984689, 820.46733773, 821.36482856,
       822.2623194 , 823.15981024, 824.05730107, 824.95479191,
       825.85228275, 826.74977358, 827.64726442, 828.54475525,
       829.44224609, 830.33973693, 831.23722776, 832.1347186 ,
       833.03220944, 833.92970027, 834.82719111, 835.72468195,
       836.62217278, 837.51966362, 838.41715445, 839.31464529,
       840.21213613, 841.10962696, 842.0071178 , 842.90460864,
       843.80209947, 844.69959031, 845.59708115, 846.49457198,
       847.39206282, 848.28955365, 849.18704449, 850.08453533,
       850.98202616, 851.879517  , 852.77700784, 853.67449867,
       854.57198951, 855.46948035, 856.36697118, 857.26446202,
       858.16195285, 859.05944369, 859.95693453, 860.85442536,
       861.7519162 , 862.64940704, 863.54689787, 864.44438871,
       865.34187955, 866.23937038, 867.13686122, 868.03435205,
       868.93184289, 869.82933373, 870.72682456, 871.6243154 ,
       872.52180624, 873.41929707, 874.31678791, 875.21427875,
       876.11176958, 877.00926042, 877.90675125, 878.80424209,
       879.70173293, 880.59922376, 881.4967146 , 882.39420544,
       883.29169627, 884.18918711, 885.08667795, 885.98416878,
       886.88165962, 887.77915045, 888.67664129, 889.57413213,
       890.47162296, 891.3691138 , 892.26660464, 893.16409547,
       894.06158631, 894.95907715, 895.85656798, 896.75405882,
       897.65154965, 898.54904049]), 'flat_field_pic': array([[ 6,  6,  7, ...,  0,  0,  1],
       [ 6,  7,  7, ...,  0,  0,  1],
       [ 6,  6,  7, ...,  1,  2,  1],
       ...,
       [ 0,  0,  0, ..., 10, 11, 12],
       [ 0,  0,  0, ...,  2,  2,  2],
       [ 0,  0,  0, ...,  0,  1,  1]], dtype=uint8), 'spec_rad_ref_luminance': 52020, 'sfit': <scipy.interpolate._interpolate.interp1d object at 0x7f379e285f40>, 'rad_fit': <scipy.interpolate._interpolate.interp1d object at 0x7f37912ab6d0>}
`

**Comment by henryliangt** [comment]
What MambaYasmin and I  @MambaYasmin were missing might be this one "rad_fit",

Please correct me, if I am wrong.
However, I am still in need of 'dark_current' attribute for my 'ProcessDatacube' object.

Could you please advise how to fix it?
@YiweiMao @christhechris

**Comment by YiweiMao** [comment]
Hi, 

1) the key `rad_fit` is the interpolation of the at sensor radiance computed from Py6S. This is not included in the calibration file by default as it will depend on your location and time of day. You will need to precompute this so the processing pipeline can use it when you want real time reflectance. 
If you don't need reflectance (set by the `processing_lvl`), the `__init__` method will not check for `rad_fit`. 

2) The pickle file is a dictionary that contains all the arrays used to calibrate the sensor. 

3) The transforms placed into the processing pipeline need some setup. `ProcessDatacube` needs to initialise some arrays depending on the `processing_lvl` one of which is `self.dark_current`. A processing level of `2` does not need convert to radiance which is why this array is missing. 
See your commented out line, `processing_lvl` is set to `4` which does this conversion after fast binning. So your problem can be solved by setting that to `4`.

**Comment by henryliangt** [comment]
![image](https://user-images.githubusercontent.com/23263731/193207531-70e23898-5337-4ba7-961e-7c8ff21d644b.png)

![image](https://user-images.githubusercontent.com/23263731/193207761-b22f2d91-afcd-4c34-9ba2-b06825a572f4.png)

Hi, I did give a try to processing_lvl=4, 
seemed worse than previous version.
looks like it is broken from here.

proced_dc = ProcessDatacube(fname = dc2, processing_lvl=4, json_path=usyd_json_path, pkl_path=usyd_pkl_path)

got an idea where to debug?


@YiweiMao

**Comment by henryliangt** [comment]
Two more questions:

1. Will we have a chance to buy the three boards to collect more data for the classifier function?
2. Will you recommend any data source for us to train a model to recognize the board 1/2/3? In case we don't have board access for data collection.

Thank you @YiweiMao

**Comment by henryliangt** [comment]
Hi Yiwei, @YiweiMao 
Thank you for the reply. I will have to test it when lab is open next Tuesday.

I have posted a question in the RobotX forum and see how they respond. 
Seemed I didn't read the painting material requirements yet just in case we wanna paint a few of them.
Can you share the paint material request? or where to buy the paints? or the paint keywords will help a lot too.

Hyperspectral sensing data looks fantastic, hope we could meet up in the contest and discuss more application solutions.

**Comment by YiweiMao** [comment]
I don't know anything more about the paints unfortunately. While I am the core developer for this Python library, I'm not competing in RobotX. I'm in the States for the rest of the year but certainly, we can meet up at USyd when I get back.

**Comment by henryliangt** [comment]
Hi, Yiwei,
Seems still need more help.
After isntall 

!pip install xarray==2022.3.0

This is the environment I am having:
![image](https://user-images.githubusercontent.com/23263731/194827369-62ef1164-5997-4ccf-91b5-eb8a3aac2125.png)
![image](https://user-images.githubusercontent.com/23263731/194827477-0884885d-18d4-4d6d-a970-e3e896523e5c.png)
![image](https://user-images.githubusercontent.com/23263731/194827560-55318596-b034-4354-b1a4-f3648cc9fb2e.png)

![image](https://user-images.githubusercontent.com/23263731/194827630-7fc1cbec-d781-4bf6-84e2-86345d39427a.png)

**Comment by henryliangt** [comment]
This is what runs out.

![image](https://user-images.githubusercontent.com/23263731/194828176-302bf3a2-ffef-437b-90fa-9b492dd05bad.png)

**Comment by henryliangt** [comment]
error level=2
![image](https://user-images.githubusercontent.com/23263731/194828614-933d5156-c21b-41a4-b525-f18358bb44b5.png)

**Comment by henryliangt** [comment]
@YiweiMao  Can you help figure out the error of rad_ref and dark_current ?

**Comment by YiweiMao** [comment]
I have a fix in the works regarding the `.opts` warning message. 
It looks like your `rad_ref` key in your calibration file is wonky and it is failing on `__init__`. Are you using the original calibration files? I'm not getting your issue on my end. 
The other thing is `xarray` actually depends on `pandas` (my version of pandas is 1.4.4 and yours is 1.5.0) - try downgrading your `pandas`. It might be something to do with how the latest version of `xarray` made breaking changes to the way it indexes. If this is the case, I'll make a version requirement for the next pypi/conda package installer.

**Comment by christhechris** [comment]
closing as seems resolved.
