### ISSUE TITLE
AttributeError: 'LucidCamera' object has no attribute 'device'

### ISSUE THREAD

**Issue by roboticsmick** [openhsi/openhsi#50]
Hi all,
Just wondering if this is still supported? Trying to get a OpenHSI with a LUCID camera running on Ubuntu 22.04. The device is recognised when I use the LUCID SDK examples, but it doesn't seem to be recognised using the OpenHSI library? Would love to get this working.

`import os
from openhsi.cameras import LucidCamera

CWD = os.getcwd()
ASSETS_FOLDER = os.path.join(CWD, "assets")
JSON_FILE = "OpenHSI-06_settings_Mono8_bin1.json"
PKL_FILE = "OpenHSI-06_calibration_Mono8_bin1.pkl"
json_path = os.path.join(ASSETS_FOLDER, JSON_FILE)
pkl_path = os.path.join(ASSETS_FOLDER, PKL_FILE)

with LucidCamera(n_lines=1000, 
                 processing_lvl = 2, 
                 pkl_path=pkl_path,json_path=json_path,
                 exposure_ms=10
                ) as cam:
    cam.collect()
     
cam.show(hist_eq=True)`

The simulated camera works. 

`Allocated 399.46 MB of RAM. There was 2243.54 MB available.
Traceback (most recent call last):
  File "/home/logic/LSSR_hyperspectral/main.py", line 18, in <module>
    cam.collect()
  File "/home/logic/LSSR_hyperspectral/venv/lib/python3.10/site-packages/openhsi/capture.py", line 46, in collect
    self.start_cam()
  File "/home/logic/LSSR_hyperspectral/venv/lib/python3.10/site-packages/openhsi/cameras.py", line 255, in start_cam
    self.device.start_stream(1)
AttributeError: 'LucidCamera' object has no attribute 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/logic/LSSR_hyperspectral/main.py", line 13, in <module>
    with LucidCamera(n_lines=1000, 
  File "/home/logic/LSSR_hyperspectral/venv/lib/python3.10/site-packages/openhsi/capture.py", line 42, in __exit__
    self.stop_cam()
  File "/home/logic/LSSR_hyperspectral/venv/lib/python3.10/site-packages/openhsi/cameras.py", line 258, in stop_cam
    self.device.stop_stream()
AttributeError: 'LucidCamera' object has no attribute 'device'`

These are the IP settings after going through the LUCID guides:

`./IpConfigUtility /list

Scanning for devices...
[index] MAC             IP              SUBNET          GATEWAY                 IP CONFIG
[0]     1C0FAF017A06    169.254.7.122   255.255.0.0     0.0.0.0                 DHCP= 1 Persistent Ip= 1 LLA = 1`

**Comment by YiweiMao** [comment]
Hi, we are continuing to support this as we use it in our research. 
We have instructions on working with the LUCID camera here (https://openhsi.github.io/openhsi/tutorials/installing_linux.html#install-lucid-vision-arena-sdk-sydney-photonicsrobonation-openhsi)
Each camera has its own python api so just checking you installed the extra dependency?

Also, tip: you can paste Python code with formatting using 
````
```python
import numpy as np
print("Hello world")
```
````

**Comment by roboticsmick** [comment]
We found the error. I think you need to change line 318 of the cameras.py from this:
class LucidCamera(OpenHSI, LucidCameraBase):
to this:
class LucidCamera(LucidCameraBase, OpenHSI):

**Comment by christhechris** [comment]
Thanks @roboticsmick, good catch. Will get a patch out ASAP.
